from helpers import *
from generator import generator
from iterator import Numbers

arrays = [[], [], []]
options = ['1', '2', '3']


def users_menu():
    users_choice = input(
        '1 - to get the lists generated by iterator\n2 - to get the lists generated by generator\n3 - to exit\n')
    if not (users_choice in options):
        print('Choose an option from the menu!')
    else:
        if users_choice == '3':
            print('The session is over!')
            return 0
        if users_choice == '1':
            for index in range(len(arrays)):
                a, b, step = interval_step_input()
                arrays[index] = [x for x in Numbers(a, b, step)]
        if users_choice == '2':
            for index in range(len(arrays)):
                a, b, step = interval_step_input()
                arrays[index] = [x for x in generator(a, b, step)]
        main_algorithm(arrays)
        for index in range(len(arrays)):
            arrays[index] = []
    return users_menu()


users_menu()
